# Generated by Django 5.1 on 2024-08-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collar_type',
            fields=[
                ('collar_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('collar_type_name', models.CharField(max_length=50)),
                ('collar_type_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='fabric',
            fields=[
                ('fabric_color', models.CharField(max_length=50)),
                ('fabric_code', models.AutoField(primary_key=True, serialize=False)),
                ('fabric_partner', models.CharField(max_length=50)),
                ('fabric_origin', models.CharField(max_length=50)),
                ('fabric_kandora', models.CharField(max_length=50)),
                ('fabric_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='front_type',
            fields=[
                ('front_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('front_type_name', models.CharField(max_length=50)),
                ('front_type_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='instruction',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructions_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='mobile_pocket_type',
            fields=[
                ('mobile_pocket_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_pocket_type_name', models.CharField(max_length=50)),
                ('mobile_pocket_type_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='pockets_type',
            fields=[
                ('pockets_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('pockets_type_name', models.CharField(max_length=50)),
                ('pockets_type_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='sleeves_type',
            fields=[
                ('sleeves_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sleeves_type_name', models.CharField(max_length=50)),
                ('sleeves_type_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='mobile_pocket',
            fields=[
                ('mobile_pocket_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_pocket_name', models.CharField(max_length=50)),
                ('mobile_pocket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.mobile_pocket_type')),
            ],
        ),
        migrations.CreateModel(
            name='suit_details',
            fields=[
                ('suit_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.collar_type')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.fabric')),
                ('front_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.front_type')),
                ('instructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.instruction')),
                ('mobile_pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.mobile_pocket')),
                ('pockets_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.pockets_type')),
                ('sleeves_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suit.sleeves_type')),
            ],
        ),
    ]
