# Generated by Django 5.1 on 2024-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collar_type',
            name='collar_type_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='front_type',
            name='front_type_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobile_pocket_type',
            name='mobile_pocket_type_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pockets_type',
            name='pockets_type_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sleeves_type',
            name='sleeves_type_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
